language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-fractaljs' ]; then cd .. && eval "mv $currentfolder generator-fractaljs" && cd generator-fractaljs; fi

